---
# Enable the Apache modules 'rewrite' and 'expires'
- name: Wordpress | Enable apache mod expires
  command: a2enmod rewrite expires
  changed_when: "'molecule-idempotence-notest' not in ansible_skip_tags"

# Install necessary prerequisite packages using 'apt' package manager
- name: Wordpress | Install required packages
  apt:
      name:
          [
              "aptitude",
              "wget",
              "libpng-dev",
              "libjpeg-dev",
              "libjpeg62-turbo-dev",
              "libfreetype6-dev",
              "gnupg",
              "mariadb-client",
          ]
      update_cache: yes
      state: present
      force_apt_get: yes
  tags: package

# Find all files in the apt cache directory and remove the files found
- name: Wordpress | Find all files in apt cache
  find:
      paths: /var/lib/apt/lists
      recurse: yes
  register: files_to_delete
- name: Wordpress | Clean apt cache
  file:
      path: "{{ item.path }}"
      state: absent
  with_items: "{{ files_to_delete.files }}"

# Configure GD library with JPEG and FreeType support for PHP
- name: Wordpress | Add jpeg and freetype support
  command: docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/
  changed_when: "'molecule-idempotence-notest' not in ansible_skip_tags"

# Install GD and MySQLi PHP extensions
- name: Wordpress | Add MySQL support
  command: docker-php-ext-install gd mysqli
  changed_when: "'molecule-idempotence-notest' not in ansible_skip_tags"

# Configure the php.ini file with the provided template
- name: Wordpress | Configure php.ini
  template:
      src: php.ini.j2
      dest: /usr/local/etc/php/php.ini
      owner: "{{ apache_user }}"
      group: "{{ apache_group }}"
      mode: 0644

# Download the wp-cli tool for managing WordPress from the official source
- name: Wordpress | Download wp-cli
  get_url:
      url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
      dest: /usr/local/bin/wp
      mode: 0750

# Copy the entrypoint script for the WordPress container
- name: Wordpress | Configure entrypoint
  copy:
      src: files/entrypoint.sh
      dest: /opt/entrypoint.sh
      mode: 0750
